# Generated by Django 5.0.2 on 2024-11-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManagementService', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendeemodel',
            name='phone_number',
            field=models.IntegerField(verbose_name='phone_number'),
        ),
    ]
