# Generated by Django 5.1.3 on 2024-11-30 17:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManagementService', '0002_alter_attendeemodel_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='event_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='event_id'),
        ),
    ]
