# Generated by Django 5.1.3 on 2024-12-02 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManagementService', '0003_alter_eventmodel_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendeemodel',
            name='event_id',
            field=models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='EventManagementService.eventmodel'),
        ),
    ]
