# Generated by Django 5.1.3 on 2024-12-02 09:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManagementService', '0004_alter_attendeemodel_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendeemodel',
            name='attendee_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='attendee_id'),
        ),
    ]
