# Generated by Django 5.1.3 on 2024-12-02 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventManagementService', '0005_alter_attendeemodel_attendee_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventmodel',
            old_name='name',
            new_name='event_name',
        ),
        migrations.RenameField(
            model_name='eventmodel',
            old_name='status',
            new_name='event_status',
        ),
    ]
