# Generated by Django 5.1.3 on 2024-12-03 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventManagementService', '0006_rename_name_eventmodel_event_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventmodel',
            old_name='event_id',
            new_name='id',
        ),
    ]
