# Generated by Django 5.1.3 on 2024-12-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManagementService', '0008_rename_attendee_id_attendeemodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendeemodel',
            name='phone_number',
            field=models.BigIntegerField(verbose_name='phone_number'),
        ),
    ]
